on: [push]

name: Docker Build and Push

jobs:
  docker-build:
    name: Docker Build and Push
    runs-on: self-hosted  # self-bootstrapped!
    steps:
    - uses: docker/setup-buildx-action@v2
      with:
        driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/ryansquared/github-runner-docker:latest-github
  docker-build-github:
    name: Docker Build and Push - GitHub Hosted
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v2
      with:
        driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/ryansquared/github-runner-docker:latest-github
